/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monkey.glb --stdout 
*/

import React from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monkey.glb')
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera makeDefault={false} far={4.87} near={4.254} position={[-1.831, 2.324, -3.508]} rotation={[-2.569, -0.43, -2.798]} />
      <mesh geometry={nodes['Link2-1'].geometry} material={materials['sandblasted aluminum']} position={[-0.016, -0.005, -0.013]} rotation={[0.265, Math.PI / 2, 0]} />
      <mesh geometry={nodes['Motor_House_Back-1'].geometry} material={materials['pw-mt11050']} position={[0.028, 0.026, -0.107]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes['Motor_House-1'].geometry} material={materials['pw-mt11050']} position={[0.028, 0.026, -0.044]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Base-1'].geometry} material={materials['pw-mt11050']} position={[0.058, 0, -0.197]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes['Gear-1'].geometry} material={materials['PW-MT11050']} position={[0.038, 0.036, -0.008]} rotation={[0.657, 0, Math.PI]} />
      <mesh geometry={nodes['Pinion-1'].geometry} material={materials['PW-MT11050']} position={[0.028, 0.031, -0.026]} rotation={[-Math.PI / 2, -0.98, -Math.PI / 2]} />
      <mesh geometry={nodes['Shaft-1'].geometry} material={materials['sandblasted aluminum']} position={[-0.028, 0.033, -0.01]} rotation={[-2.876, Math.PI / 2, 0]} />
      <mesh geometry={nodes['Link3-1'].geometry} material={materials['sandblasted aluminum']} position={[-0.028, 0.2, -0.106]} rotation={[-0.485, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['Link3-3'].geometry} material={materials['sandblasted aluminum']} position={[0.086, 0.186, -0.18]} rotation={[-0.904, Math.PI / 2, 0]} />
      <mesh geometry={nodes['Link4-3'].geometry} material={materials['sandblasted aluminum']} position={[0.082, 0.025, -0.187]} rotation={[0.578, 0, 0]} />
      <mesh geometry={nodes['Link2-2'].geometry} material={materials['sandblasted aluminum']} position={[0.073, 0.068, 0.007]} rotation={[-2.876, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['Tail-2'].geometry} material={materials['pw-mt11050']} position={[0.106, 0.111, 0.02]} />
      <mesh geometry={nodes['Link4-1'].geometry} material={materials['sandblasted aluminum']} position={[-0.026, 0.026, -0.189]} rotation={[0.843, 0, 0]} />
      <mesh geometry={nodes['Spacer-2'].geometry} material={materials['pw-mt11050']} position={[-0.022, 0.033, -0.187]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['Spacer-1'].geometry} material={materials['pw-mt11050']} position={[0.058, 0.033, -0.187]} rotation={[0.558, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['Right_Hand20-1'].geometry} material={materials['pw-mt11050']} position={[0.105, 0.225, -0.185]} rotation={[-0.904, -Math.PI / 2, 0]} />
      <mesh geometry={nodes['Left_Hand20-1'].geometry} material={materials['pw-mt11050']} position={[-0.047, 0.225, -0.12]} rotation={[-0.485, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/monkey.glb')
