export const MODEL_CONFIG = {
  url: "/models/monkey.glb",
  loopSeconds: 10,
  targetSizeDesktop: 5.2,
  targetSizeMobile: 4.2,
  rotationOffset: [0, 0, 0] as [number, number, number],
  positionOffset: [0, 0, 0] as [number, number, number],
  scaleMultiplier: 0.9,
  scroll: {
    desktopSectionVh: 420,
    mobileSectionVh: 300,
    desktopCycles: 2,
    mobileCycles: 1,
    desktopDamping: 6,
    mobileDamping: 8,
    motionStart: 0.12,
    motionEnd: 0.82,
    presentationStart: 0.18,
    presentationEnd: 0.9,
    cameraStart: 0.58,
    cameraEnd: 0.9,
    cameraEndZ: 7.25,
  },
};
